### PR TITLE
Bump version to 3.4.0

### PR DESCRIPTION
**Pull request by helentsui**
Hello, I'd like to bump the version to 3.4.0 so that I could use the changes brought in by this commit https://github.com/tinymce/tinymce-react/commit/3fef7b7c29abcb34ac64ffdd8d4e1c3f88bace1e. I'm trying to use the getCharacterCount API, which is not available in tinymce version 5.0.4.

### CODE REVIEW

**Comment by lnewson** [comment]
@helentsui that commit doesn't make any changes for the wordcount plugin, nor it's `getCharacterCount` API so this won't help you there. Additionally this package doesn't define the version of TinyMCE being used, it's either loaded from the cloud or it'll use whatever version you've packaged locally. As such releasing that won't help you, since you're on 5.0.4. Given you're still on 5.0.4 I'll assume you're bundling TinyMCE yourself, so you'll need to upgrade your TinyMCE dependency instead to fix that issue.

**Comment by helentsui** [comment]
That commit bumps tinymce to 5.1.5, and `getCharacterCount` was added in 5.0.6.

I don't have tinymce in my package.json though so I don't believe I'm bundling it. I also don't see it in my package-lock.json file.

**Comment by lnewson** [comment]
That's a dev dependency and only used for running tinymce-react's tests. Additionally it previously was `^5.0.4` which means by default it would have installed the latest version anyway, so we only bumped the minimum version used for testing and as such it's not what your application will be using. Can you provide a code sandbox or something similar to show the issue you're having?

**Comment by helentsui** [comment]
Ah, found the issue. I was loading tinymce through an external script tag, and that was bringing in the wrong version. Closing this PR.

**Comment by lnewson** [comment]
Cool, glad to hear you got it sorted out 👍

**Pull request closed without merging**
