### PR TITLE
Add formElementName to rendered textarea

### PR DESCRIPTION
**Pull request by gzzo**
See #37

### CODE REVIEW

**Comment by fyrkant** [comment]
Does this compile? I think you have to add the prop to the EditorPropTypes.ts file as well.

**Comment by fyrkant** [comment]
Could the prop be simplified to `name` instead? 🤔

**Comment by fyrkant** [comment]
Also, add a test to the Editor.test.tsx file checking that the textarea really gets the attribute.

**Comment by gzzo** [comment]
@fyrkant I added tests and added the prop to EditorPropTypes.

Regarding the name, there is already a prop called `tagName` which is used when rendering inline, I think it makes sense to be explicit in this case that this prop will only apply to the textarea.  How about `textareaName`?

**Comment by fyrkant** [comment]
`textareaName` sounds good to me!

**Comment by fyrkant** [comment]
Awesome, than you! I'll merge this and make a release a new version on npm.

**Pull request merged**
