### PR TITLE
Add Shadow DOM support

### PR DESCRIPTION
**Pull request by rkbhochalya**

### CODE REVIEW

**Comment by fyrkant** [comment]
Not sure if this should be the default, but maybe a setting? A `useTarget` boolean prop or something like that, what do you think?

**Comment by rkbhochalya** [comment]
@fyrkant I don't see any potential issue using `target` by default. It's an internal thing and doesn't affect the way the `Editor` is used. Or does it?

**Comment by fyrkant** [comment]
Talked this over with my colleague and you're right this should work as a default so if you just sign the CLA I can merge this! 🎉

**Comment by rkbhochalya** [comment]
@fyrkant done!

**Pull request merged**
